version: '3'

# docker-compose up
# docker rm $(docker ps -a -q) && docker volume prune -f
# mysql -h 172.17.0.1 -u docker_user -p docker_database_name

services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "123456789"
      MYSQL_DATABASE: sites
    ports:
      - '3306:3306'
    volumes:
      - './_sql/:/docker-entrypoint-initdb.d/'